### ISSUE TITLE
Crash in swipe-dismiss library

### ISSUE THREAD

**Issue by remulasce** [remulasce/metroapp#225]
NullPointer exception SDLVTL:209

in Android fxn AdapterView.getPosition

Occurs on app startup.
Observed twice in past 7 days.

It seems like this should be just a random rare occurance, but twice in a week makes me think otherwise.

Might have to delay dev_4 to include a fix.

It's lame because it's in the opensource swipe library. Which his proved pretty problematic so far.

**Comment by remulasce** [comment]
USER_COMMENT=
ANDROID_VERSION=4.3.1
APP_VERSION_NAME=0.75
BRAND=htc
PHONE_MODEL=EVO
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException
at android.widget.AdapterView.getPositionForView(AdapterView.java:597)
at com.remulasce.lametroapp.libraries.SwipeDismissListViewTouchListener.onTouch(SwipeDismissListViewTouchListener.java:209)
at android.view.View.dispatchTouchEvent(View.java:7386)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1940)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2228)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1471)
at android.app.Activity.dispatchTouchEvent(Activity.java:2424)
at com.remulasce.lametroapp.MainActivity.dispatchTouchEvent(MainActivity.java:376)
at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:268)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2176)
at android.view.View.dispatchPointerEvent(View.java:7571)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3883)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3778)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5419)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5399)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5370)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5493)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:132)
at android.os.Looper.loop(Looper.java:124)
at android.app.ActivityThread.main(ActivityThread.java:5289)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
at dalvik.system.NativeStart.main(Native Method)

**Comment by nighelles** [comment]
Wow, what the hell? Do you have to use an open source library just to
/detect/ swipe motions?

**Comment by remulasce** [comment]
Yes. I mentioned that to you. That was my example of why it was bogus that
Android makes you use 3rd party libraries.

**Comment by nighelles** [comment]
That's super lame.

**Comment by remulasce** [comment]
That's what you said last time

**Comment by nighelles** [comment]
Sounds like something I'd say.

**Comment by nighelles** [comment]
Can you reproduce it? Is it like, if you try to swipe while the app is loading?
